[tool.poetry]
name = "dtlr-nmt"
version = "0.1.0"
description = "Digital Techniques for Language Revival: Neural Machine Translation API"
authors = ["Jack Han jcdhan@proton.me"]

[tool.poetry.dependencies]
python = "^3.11"
flask = "3.0.3"
flask-cors = "5.0.0"
numpy = "<2.0.0"
torch = "2.2.2"
argostranslate = "1.11.0"
gunicorn = "23.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "8.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

